# Generated by Django 6.0.4 on 2026-04-17 15:04

import django.db.models.deletion
from django.db import migrations, models

import friese_mcp.contrib.oauth.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated OAuth client identifier.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated OAuth client secret.  Treat as a password.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this client (e.g. 'claude-agent', 'gpt-mcp-client').",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive clients cannot obtain new tokens; existing tokens are rejected.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="mcp",
                        help_text="Space-separated list of permitted scopes for this client.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OAuth Client",
                "verbose_name_plural": "OAuth Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated Bearer token secret.  Treat as a password.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=friese_mcp.contrib.oauth.models._default_expires_at,
                        help_text="Token expiry time.  Tokens past this time are rejected.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="mcp",
                        help_text="Space-separated list of scopes granted to this token.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="OAuth client that obtained this token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="friese_mcp_oauth.oauthclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Access Token",
                "verbose_name_plural": "OAuth Access Tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
