# Generated by Django 5.2.13 on 2026-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friese_mcp_oauth", "0004_permission_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthclient",
            name="client_secret",
            field=models.CharField(
                editable=False,
                help_text="HMAC-SHA256 of the raw client secret keyed by SECRET_KEY.  Never the raw value.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
