# Generated by Django 6.0.4 on 2026-06-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrisianMcpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated Bearer token secret.  Treat as a password.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this token (e.g. 'claude-agent', 'staging-client').",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tokens are rejected by the authentication class.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Updated automatically each time the token authenticates a request.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional user associated with this token.  Leave blank for service tokens.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frisian_mcp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Frisian MCP Token",
                "verbose_name_plural": "Frisian MCP Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="frisianmcptoken",
            index=models.Index(fields=["token", "is_active"], name="frisian_mcp_tok_active_idx"),
        ),
        migrations.AddField(
            model_name="frisianmcptoken",
            name="permission",
            field=models.CharField(
                choices=[("read", "Read Only"), ("read_write", "Read Write"), ("admin", "Admin")],
                default="read_write",
                help_text="Controls which tier of tools this token can access: Read Only (read tools only), Read Write (read + write tools), or Admin (all tools).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="frisianmcptoken",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="HMAC-SHA256 of the raw Bearer token keyed by SECRET_KEY.  Never the raw value.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
