# Generated by Django 5.2.13 on 2026-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friese_mcp_tokens", "0003_friesemcptoken_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friesemcptoken",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="HMAC-SHA256 of the raw Bearer token keyed by SECRET_KEY.  Never the raw value.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
