# Generated by Django 6.0.4 on 2026-06-02 10:37

import hashlib
import hmac as _hmac_lib
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import frisian_mcp.contrib.oauth.models


def _hmac_secret(raw: str) -> str:
    """Mirror of contrib.oauth.models._hmac_secret for this migration only."""
    hmac_key: str = getattr(settings, "FRISIAN_MCP_HMAC_KEY", "") or settings.SECRET_KEY
    return _hmac_lib.new(hmac_key.encode(), raw.encode(), hashlib.sha256).hexdigest()


def _hash_existing_tokens(apps: Any, schema_editor: Any) -> None:
    """Replace plaintext OAuthAccessToken.token values with their HMAC digest."""
    OAuthAccessToken = apps.get_model("frisian_mcp_oauth", "OAuthAccessToken")
    for row in OAuthAccessToken.objects.all().iterator():
        digest = _hmac_secret(row.token)
        if digest == row.token:
            continue
        row.token = digest
        row.save(update_fields=["token"])


def _noop_reverse(apps: Any, schema_editor: Any) -> None:
    """Reverse migration intentionally no-op: HMAC is one-way."""


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated OAuth client identifier.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated OAuth client secret.  Treat as a password.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this client (e.g. 'claude-agent', 'gpt-mcp-client').",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive clients cannot obtain new tokens; existing tokens are rejected.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="mcp",
                        help_text="Space-separated list of permitted scopes for this client.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OAuth Client",
                "verbose_name_plural": "OAuth Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated Bearer token secret.  Treat as a password.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=frisian_mcp.contrib.oauth.models._default_expires_at,
                        help_text="Token expiry time.  Tokens past this time are rejected.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="mcp",
                        help_text="Space-separated list of scopes granted to this token.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="OAuth client that obtained this token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="frisian_mcp_oauth.oauthclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Access Token",
                "verbose_name_plural": "OAuth Access Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="oauthaccesstoken",
            index=models.Index(fields=["token", "expires_at"], name="frisian_mcp_oat_expires_idx"),
        ),
        migrations.AddField(
            model_name="oauthaccesstoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent authenticated request using this token.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oauthclient",
            name="permission",
            field=models.CharField(
                choices=[("read", "Read Only"), ("read_write", "Read Write"), ("admin", "Admin")],
                default="read_write",
                help_text="Controls which tier of tools tokens issued to this client can access: Read Only, Read Write, or Admin.",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="oauthclient",
            name="scope",
        ),
        migrations.AddField(
            model_name="oauthaccesstoken",
            name="permission",
            field=models.CharField(
                choices=[("read", "Read Only"), ("read_write", "Read Write"), ("admin", "Admin")],
                default="read_write",
                help_text="Permission tier inherited from the issuing client at token creation time.",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="oauthaccesstoken",
            name="scope",
        ),
        migrations.AlterField(
            model_name="oauthclient",
            name="client_secret",
            field=models.CharField(
                editable=False,
                help_text="HMAC-SHA256 of the raw client secret keyed by SECRET_KEY.  Never the raw value.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.RunPython(
            code=_hash_existing_tokens,
            reverse_code=_noop_reverse,
        ),
        migrations.AlterField(
            model_name="oauthaccesstoken",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="HMAC-SHA256 of the raw Bearer token keyed by SECRET_KEY.  Never the raw value — the raw token is exposed exactly once via ``plaintext_token`` on the freshly-saved instance and is never persisted, so a leaked DB row is not directly exploitable.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="oauthclient",
            name="redirect_uris",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Registered OAuth 2.0 redirect URIs (RFC 6749 §3.1.2).  The authorize endpoint requires an exact-match against this list before issuing an authorization code (SEC-2).  An empty list disables the authorize endpoint for this client; populate it via Django admin, RFC 7591 dynamic registration, or set ``FRISIAN_MCP_OAUTH_PKCE_AUTO_REGISTER=True`` to permit on-demand PKCE clients (HTTPS / loopback validation still applies).",
            ),
        ),
        migrations.AlterField(
            model_name="oauthclient",
            name="client_id",
            field=models.CharField(
                editable=False,
                help_text="OAuth client identifier — auto-generated (32 hex chars) or supplied by the client.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="oauthclient",
            name="grant_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Allowed OAuth 2.0 grant types for this client (RFC 7591 §2).  An empty list means no restriction — all supported grant types ("client_credentials", "authorization_code") are permitted.  Set to ["client_credentials"] for service-to-service clients that should never use the PKCE flow, or ["authorization_code"] for browser/native clients that should not use client_credentials.',
            ),
        ),
        migrations.AlterField(
            model_name="oauthclient",
            name="grant_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Allowed OAuth 2.0 grant types for this client (RFC 7591 §2).  An empty list means no restriction — all supported grant types (``client_credentials``, ``authorization_code``) are permitted.  Set to ``[\\"client_credentials\\"]`` for service-to-service clients that should never use the PKCE flow, or ``[\\"authorization_code\\"]`` for browser/native clients that should not use client_credentials.',
            ),
        ),
    ]
