# Generated by Django 6.0.4 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("friese_mcp_oauth", "0001_initial"),
        ("friese_mcp_tokens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Human-readable label for this agent connection "
                            "(e.g. 'Claude Code \u2014 production')."
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("claude-code", "Claude Code"),
                            ("cursor", "Cursor"),
                            ("gpt", "GPT"),
                            ("github-copilot", "GitHub Copilot"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        help_text="The type of coding agent or MCP client.",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Inactive connections are ignored by the gateway. "
                            "Linked credentials remain valid but tool filtering is disabled."
                        ),
                    ),
                ),
                (
                    "allowed_tools",
                    models.JSONField(
                        blank=True,
                        help_text=(
                            'Optional JSON array of tool names this agent may see and call '
                            '(e.g. ["users.list", "workouts.create"]). '
                            "Leave blank to allow all registered tools."
                        ),
                        null=True,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent tools/call request from this agent.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text notes (owner, purpose, rotation schedule, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "oauth_client",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "OAuth 2.0 client credential for this agent. "
                            "Set either this or token \u2014 not both."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_connections",
                        to="friese_mcp_oauth.oauthclient",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Static Bearer token credential for this agent. "
                            "Set either this or oauth_client \u2014 not both."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_connections",
                        to="friese_mcp_tokens.friesemcptoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Connection",
                "verbose_name_plural": "Agent Connections",
                "ordering": ["-created_at"],
            },
        ),
    ]
